name: Android CI

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Install Gradle 8.7
        uses: gradle/actions/setup-gradle@v3
        with:
          gradle-version: 8.7

      - name: Generate Gradle 8.7 wrapper
        run: gradle wrapper --gradle-version 8.7

      - name: Build Debug APK
        run: ./gradlew assembleDebug

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: GroceryApp-Debug
          path: app/build/outputs/apk/debug/app-debug.apk          name: GroceryApp-Debug
          path: app/build/outputs/apk/debug/app-debug.apk
