name: Android CI

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Install Gradle
        run: sudo apt-get update && sudo apt-get install -y gradle

      - name: Generate Gradle wrapper
        run: gradle wrapper

      - name: Build Debug APK
        run: ./gradlew assembleDebug

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: GroceryApp-Debug
          path: app/build/outputs/apk/debug/app-debug.apk
